### ISSUE TITLE
Marseille misspelled in config/realaddress.php

### ISSUE THREAD

**Issue by t-grm** [nonsapiens/addressfactory#1]
Hi,
Just wanted to point out that "_Marseille_", the French city, does ***not*** take a trailing "s" :)
You may refer to its [WikiPedia Page](https://fr.wikipedia.org/wiki/Marseille) for the exact spelling.

**Comment by nonsapiens** [comment]
Hey, thanks for letting me know - I've corrected it accordingly :-)

**Comment by t-grm** [comment]
You're welcome!
Thanks for the excellent package
