### ISSUE TITLE
Update to V7

### ISSUE THREAD

**Issue by casperwilkes** [nonsapiens/addressfactory#7]
I was wondering if this repo was going to be updated to verson 7?

**Comment by casperwilkes** [comment]
Right now, it fails the upgrade process because of the dependency on `illuminate/support: ~5.1`

**Comment by stesvis** [comment]
Same here, nothing i tried worked.

**Comment by stuartsteedman** [comment]
Hi folks,

I will be updating this for L8 support, which should - in theory - work with L7 too ...

**Comment by casperwilkes** [comment]
@stuartsteedman , check out my comments on another issue, that'll give you a stable release for v7, but i assume would work for v8 as well: https://github.com/nonsapiens/addressfactory/issues/5#issuecomment-606956684

**Comment by stuartsteedman** [comment]
> @stuartsteedman , check out my comments on another issue, that'll give you a stable release for v7, but i assume would work for v8 as well: [#5 (comment)](https://github.com/nonsapiens/addressfactory/issues/5#issuecomment-606956684)

Yes:  you can get the new package here:  https://github.com/nonsapiens/realaddressfactory
Fully supports all latest Laravel versions
