### ISSUE TITLE
Update to v8?

### ISSUE THREAD

**Issue by Xodus-CO** [nonsapiens/addressfactory#8]
Seems like this is abandoned as there is an open issue to update to v7.

Hoping it gets a little love and is usable again.

**Comment by stuartsteedman** [comment]
Hi there,

The project was neglected for a while, but I am putting together a brand new version of AddressFactory that runs on L8 ... stay tuned!

**Comment by harryqt** [comment]
Hey, any updates?

**Comment by stuartsteedman** [comment]
> Hey, any updates?

Yes:  you can get the new package here:  https://github.com/nonsapiens/realaddressfactory
Fully supports all latest Laravel versions

**Comment by harryqt** [comment]
Thank you!
