### ISSUE TITLE
Add limits for requests

### ISSUE THREAD

**Issue by dariusvelavicius** [nonsapiens/addressfactory#9]
Hi,

this is a nice thing and I used it and was happy until I changed the configuration to add some extra cities for US, ran the script to generate 500 addresses on Friday afternoon and went home hapily. Woke up to 2 emails from Google to find my bank account completely empty and additional 1500 USD that I owe Google. Something went wrong and the script ran for 1.5 days and generated 700 000+ requests. I know this is on me to set up billing plan and quotas to make sure this don't happen but it would be very nice to have some extra checks on this line - https://github.com/nonsapiens/addressfactory/blob/master/src/RealAddress.php#L154 - and maybe some configuration like number of requests allowed, throttling and so on. 

After I noticed this I disabled the API but the script was still running - it generated additional 9 million requests (all of them resulted in an error) per day and 160 GB error file in the server :) 

I'd like to contribute to this project so I was thinking to add two things:

1. set a configuration option to only allow max number of requests to generate one address. Something like 10 - if after 10 tries it still cannot retrieve a valid city, it would fail.
2. set a configuration option to throttle the requests in that while loop. Something like wait 1 second after each 10 tries.

What do you guys think?

**Comment by stuartsteedman** [comment]
This package's successor, RealAddressFactory, now has rate limiting as requested:

https://github.com/nonsapiens/realaddressfactory
